[package]
name = "sv2_ffi"
version = "2.1.0"
authors = ["The Stratum V2 Developers"]
edition = "2018"
description = "SV2 FFI"
documentation = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[lib]
crate-type = ["staticlib"]

[dependencies]
codec_sv2 = { path = "../codec-sv2", version = "^2.0.0" }
binary_sv2 = { path = "../binary-sv2", version = "^3.0.0" }
common_messages_sv2 = { path = "../subprotocols/common-messages", version = "^5.0.0" }
template_distribution_sv2 = { path = "../subprotocols/template-distribution", version = "^3.0.0" }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1"

[features]
prop_test = ["binary_sv2/prop_test", "common_messages_sv2/prop_test", "template_distribution_sv2/prop_test"]
