default: 
  environment: production 
  mining: 
    algorithm: scrypt 
    threads: auto 
    intensity: auto 
  pools: 
    - url: stratum+tcp://doge.zsolo.bid:8057 
      username: YOUR_WALLET_ADDRESS 
      password=os.getenv("POOL_PASSWORD", "x")"POOL_PASSWORD", "x") 
      algorithm: scrypt 
      priority: 1 
      timeout: 30 
      retry_attempts: 3 
      enable_tls: false 
  hardware: 
    type: asic 
    device_ids: [] 
    power_limit: null 
    temperature_limit: 80 
    fan_speed: null 
    frequency: null 
    voltage: null 
  economic: 
    enabled: true 
    max_power_cost: 0.12 
    min_profitability: 0.01 
    shutdown_on_unprofitable: true 
    profitability_check_interval: 300 
    wallet_address: YOUR_WALLET_ADDRESS 
    auto_withdrawal_threshold: 0.01 
  security: 
    enable_encryption: true 
    wallet_encryption_key=os.getenv("API_KEY", "your_key_here")"API_KEY", "your_key_here") 
    rate_limiting_enabled: true 
    max_requests_per_minute: 60 
    enable_ddos_protection: true 
    tls_verify: true 
    allowed_ips: 
      - 127.0.0.1 
  monitoring: 
    enabled: true 
    metrics_port: 8080 
    health_check_port: 8081 
    enable_prometheus: true 
    enable_grafana: false 
    alert_webhook: null 
    log_performance_metrics: true 
  performance: 
    auto_tune_enabled: true 
    benchmark_interval: 3600 
    hash_rate_optimization: true 
    power_optimization: true 
    thermal_throttling_enabled: true 
    max_temperature: 85 
  logging: 
    level: INFO 
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 
    file_path: logs/mining.log 
    max_file_size: 10485760 
    backup_count: 5 
    enable_structured_logging: true 
    enable_console: true 
production: 
  logging: 
    level: WARNING 
    file_path: logs/mining.log 
