# Mining Configuration File
# This file contains the core configuration for the mining system

# Server Configuration
server:
  host: "127.0.0.1"
  port: 31415
  ssl_enabled: false
  ssl_certfile: null
  ssl_keyfile: null

# Mining Configuration
mining:
  worker_name: "rig01"
  minimum_payout_threshold: 0.005
  max_temperature: 80.0
  min_profit_margin_pct: 0.5

# Pool Configuration
pools:
  - name: "f2pool_ltc"
    url: "stratum+tcp://ltc.f2pool.com:8888"
    username: "ltc1qpptg85asckrjy9ygygh2tfgxqwzn6672zmzq99"
    password: "rig01"
    algorithm: "scrypt"
    priority: 1
    
  - name: "zsolo_doge"
    url: "stratum+tcp://doge.zsolo.bid:8057"
    username: "DGKsuHU6XdghZtA2aWGqvrZrkWracQJzPd"
    password: "rig01"
    algorithm: "scrypt"
    priority: 2

# Security Configuration
security:
  enable_rate_limiting: true
  max_requests_per_minute: 60
  enable_ddos_protection: true
  allowed_origins:
    - "http://localhost:31415"
    - "http://127.0.0.1:31415"
    - "https://localhost:31415"
    - "https://127.0.0.1:31415"

# Database Configuration
database:
  enabled: true
  uri: "sqlite:///mining_data.db"
  name: "mining_db"
  collections:
    mining_stats: "mining_statistics"
    system_metrics: "system_metrics"
    pool_stats: "pool_statistics"

# Monitoring Configuration
monitoring:
  collection_interval: 5
  health_check_interval: 60
  enable_prometheus: true
  prometheus_port: 9090

# Hardware Configuration
hardware:
  enable_asic_emulation: true
  enable_gpu_mining: true
  temperature_limit: 85
  power_limit: 200
  fan_speed_auto: true

# Economic Guardian Configuration
economic:
  enable_guardian: true
  min_profit_usd_per_day: 1.0
  max_loss_usd_per_day: 10.0
  electricity_cost_kwh: 0.12
  check_interval: 300

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "mining.log"
  max_size_mb: 100
  backup_count: 5