# C source files
filegroup(
    name = "c_sources",
    srcs = glob([
        "*.c",
    ]),
    visibility = ["//visibility:public"],
)

# OpenCL source files
filegroup(
    name = "opencl_sources",
    srcs = glob([
        "*.comp",
    ]),
    visibility = ["//visibility:public"],
)